# This workflow will build a docker container, publish it to IBM Container Registry, and deploy it to IKS when a release is created
#
# To configure this workflow:
#
# 1. Ensure that your repository contains docusaurus config
# 2. Setup secrets in your repository by going to settings: Create BUCKET_NAME, IBM_CLOUD_API_KEY and PUBLIC_ENDPOINT

name: Build and Deploy docs to IBM Cloud

on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: us-south
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  PUBLIC_ENDPOINT: ${{ secrets.PUBLIC_ENDPOINT }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Download and Install IBM Cloud CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f cloud-object-storage

      # Authenticate with IBM Cloud CLI
      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g Default
          ibmcloud target -r ${IBM_CLOUD_REGION}
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3
        with: 
           node-version: '12'
      - run:  npm install -g yarn

      # Build the Docusaurus documentation
      - name: Build the documentation
        run: |
          yarn global add docusaurus
          yarn build

      # Publish the build files to the IBM COS
      - name: Publish to IBM COS
        run: |
          scripts/ibm_deploy.sh build
